pacocoursey/next-themes

README.md
Although obvious from the context, adding the import into the example aids people copying and pasting to quickly test it out.
=> Update useTheme example to explicitly import the hook

index.tsx
Recently started using the package in a Next project to replace a custom solution - thanks for making it!
Have seen some errors coming through in Sentry relating to `localStorage.getItem()`
```
TypeError
Cannot read property 'getItem' of null
```
I guess when people have certain security settings, use incognito mode or have a very old browser?
It seems like the `<NextHead>` scripts added via `dangerouslySetInnerHTML` already error-trap their `localStorage` calls, but not elsewhere?
Added a `try/catch` block inside the `getTheme()` function in this PR to handle unsupported browsers.
**Edit:**
Just updated the `<ThemeProvider>` render method, adding a `try/catch`  there too for `localStorage.setItem()`
=> Handle error for missing localStorage

package.json
This package works with React 17, so updating peerDependencies to avoid incorrect warning during `npm install` or `yarn install`.
=> Update peerDependencies to avoid incorrect warnings

README.md, package.json
While working on #12 I noticed that some information are not visible here on GitHub and also on NPM.
For example on the NPM page I would expect to see the repository-url and on here expect to see the latest version of the package. In order to add this info I created this PR.
- add version badge to readme that shows the version number of the package published on npm
- add link to the GitHub repository, so that on NPM the repository is listed
=> Improve readme and link to GitHub repository on NPM

index.tsx
Hey thanks for the project 😃
When you (or a user) deletes the localStorage value manually via dev tools or otherwise, the value is set as `null` and no themes are used. 
Example:
It seems like this should revert to defaultValue if it's set in the provider and never be set to null.
=> Use default theme if localstorage value deleted manually 

README.md
This example will avoid layout shift because the `width`/`height` remain the same – only the `src` is swapped.
Additionally we add a transparent gif placeholder until we can determine if the theme is dark or light.
=> Update readme with `next/image` example

src/index.tsx
When using `attribute: 'class'`, the inserted script tag will be:
```html
<script>
!function(){try {
var d=document.documentElement.classList;
d.remove('light','dark');
var e=localStorage.getItem('theme');
if("system"===e||(!e&&true)){
var t="(prefers-color-scheme: dark)",m=window.matchMedia(t);
if(m.media!==t||m.matches){
d.style.colorScheme = 'dark';
d.add('dark')
}else{
d.style.colorScheme = 'light';
d.add('light')}
}else if(e){
d.add(e|| '')
}
if(e==='light'||e==='dark')
d.style.colorScheme=e
}catch(e){}
}()
</script>
```
...where `d=document.documentElement.classList` but later it tries to access its `style` property via `d.style.colorScheme`. Should be using `document.documentElement` here instead.
This PR changes it to explicitly use `d` for `document.documentElement` and `c` for …
=> Fix `d.style` being undefined and code golf

.github/workflows/e2e.yml, .github/workflows/test.yml, e2e/example.test.ts, e2e/forced-theme.test.ts, e2e/storage-event.test.ts, e2e/switch-theme.test.ts, e2e/system-theme.test.ts, e2e/util.ts, examples/example/pages/index.js, jest.config.js, package.json, playwright.config.ts, yarn.lock
Adds an e2e test-suite with a playwright configuration. The use-cases listed below are covered at this point:
- rendering persisted themes
- switching themes
- rendering forced themes
- updating theme based on storage-event originating in different tab
- updating theme based on a previously executed storage-event which was delayed due to forced-theme
=> Add a Playwright e2e test-suite

README.md
Using `resolvedTheme` will cause the select to show `light` or `dark` when `system` is selected rather than `system` as expected.
That is, if you use the example as-is, if the theme is `system` the `resolvedTheme` will be `light` or `dark`, so `system` can never be selected in the `<select>`
=> Fix README hydration ThemeSwitcher example

README.md
The previous documentation referred to using `<ThemeProvider defaultTheme="system">`, but this is no longer necessary
=> Update documentation around `defaultTheme`

src/index.tsx
Every time `<Theme />` renders, a new object is constructed and passed to `ThemeContext.Provider`. This guarantees that regardless of what inputs changed the Context will be propagated. This is particularly harmful when React is doing hydration because if an unhydrated Suspense boundary exists in the sub-tree of the Provider it will fall back to client rendering regardless of whether the context is an actual dependency for that Suspense boundary.
This commit adds memoization so the value only changes if one of it's inputs change To make this memoization effective the default argument for `themes` needed to be statically extracted (it constructs a new array on each function invocation otherwise)
=> Memoize ThemeContext.Provider value

README.md
This just adds information about how to use `next-themes` in the new `app/` directory.
=> Update README with instructions for Next.js 13 appDir

README.md
Some minor clarity and link in the README to help save time for people trying to use next-themes in a CSS file with Tailwind.
=> Update README with note for HTML class attribute

packages/next-themes/src/types.ts
Port #177 because I couldn't figure out how to update the PR myself…
=> fix: add explicit undefined type to support exactOptionalPropertyTypes option (Port #177)

examples/with-app-dir/.gitignore, examples/with-app-dir/README.md, examples/with-app-dir/next.config.js, examples/with-app-dir/package.json, examples/with-app-dir/postcss.config.js, examples/with-app-dir/src/app/globals.css, examples/with-app-dir/src/app/layout.tsx, examples/with-app-dir/src/app/page.tsx, examples/with-app-dir/src/components/ThemeProvider.tsx, examples/with-app-dir/src/components/ThemeToggle.tsx, examples/with-app-dir/tailwind.config.ts, examples/with-app-dir/tsconfig.json, pnpm-lock.yaml
@pacocoursey should we also have a demo app on Vercel for this?
=> chore: adds a new example app called 'with-app-dir'

packages/next-themes/tsup.config.js
Adds a `"use client"` banner to the output code to avoid re-exporting it as a client module.
It simplifies the process on not having the Step 2 as described at https://ui.shadcn.com/docs/dark-mode/next.
Also it doesn't break older version because it is just a string which would be ignored anyways
=> fix: add 'use client' to output code

examples/example/pages/dark.js, examples/example/pages/index.js, examples/example/pages/light.js, next-themes/src/index.tsx, next-themes/src/script.ts, next-themes/src/types.ts
By moving it to a separate file and using `script.toString()` we get minification for free. Much more maintainable than the extremely messy inline script logic we had.
=> Improved inline script minification

next-themes/src/index.tsx
As of version `0.3.0` I am getting a type error while trying to use ThemeProvider, I fixed it by manually adding return types to ThemeProvider
=> fix: manually type ThemeProvider to fix type errors

README.md
This pull request updates the anchor link in the Readme.md file to ensure proper scrolling to the intended position on the test page.
- Changed the anchor link from ###tailwind to #tailwind in the Readme.md file. (the origin is: https://github.com/pacocoursey/next-themes###with-tailwind)
=> Update anchor link in Readme.md for proper scrolling

README.md
was fixed in https://github.com/pacocoursey/next-themes/pull/186
=> mention `next-themes` is react agnostic

license.md
In PR #269 I moved both Readme and License in npm package and symlinked them in root repo, The Readme has no issues, but the License doesn't render in github's web UI.
So I have changed the License to a normal file again. There is a license in npm package and it is also copied in root. The License will rarely change to it is ok to keep it like that.
=> chore: make license a file again as github doesn't render it

next-themes/src/types.ts
Make `children` optional. Because children are not required, as in the following usage, `children` is not passed in explicitly. We can ensure that types is compatible with the original version.
```tsx
const baseContexts: JSX.Element[] = [
<ThemeProvider key="themeProvider" />, // here, `children` is not passed.
<JotaiStoreProvider key="jotaiStoreProvider" />,
]
export function WebAppProviders({ children }: PropsWithChildren) {
return (
<ProviderComposer contexts={baseContexts}>
{children}
</ProviderComposer>
)
}
export const ProviderComposer: Component<{
contexts: JSX.Element[]
}> = ({ contexts, children }) => {
return contexts.reduceRight((kids: any, parent: any) => {
return React.cloneElement(parent, { children: kids })
}, children)
}
```
Thanks, @pacocoursey
=> fix: make `children` optional

next-themes/package.json, next-themes/tsup.config.ts
Currently the bundler produces several files, I have made it so that everything is bundled in 4 files for single point of import for mjs, cjs and dts.
=> feat: Output bundled index.{js,mjs,d.ts,d.mts} file instead of seprate files

next-themes/package.json
Thanks a lot for this package
I get the following warning from pnpm after upgrading to NextJS v15 (released today), which installs react 19 RC
React 19 is technically still in RC stage, but since a stable version of a major Metaframework is installing it, it's a sign that it's ready for production use and will now be used by many projects.
```ts
│ └─┬ next-themes 0.3.0
│   ├── ✕ unmet peer react@"^16.8 || ^17 || ^18": found 19.0.0-rc-65a56d0e-20241020
│   └── ✕ unmet peer react-dom@"^16.8 || ^17 || ^18": found 19.0.0-rc-65a56d0e-20241020
```
=> feat: add react v19 to peer deps

next-themes/__tests__/index.test.tsx, next-themes/src/script.ts
PR #275 added support for multiple attributes in applyTheme, but missed handling it in the injection script. This caused page flashes when attribute prop is an array in ThemeProvider. This PR fixes that.
=> fix: support multiple attributes in the injection script

next-themes/README.md
Closes #250 
@pacocoursey We should probably also update the examples. As they're outdated anyways, I'll update them fully in a upcoming PR.
=> docs: update docs on how to use with tailwindcss >3.4.1

.github/workflows/e2e.yml, .github/workflows/test.yml
PNPM versioning is quite the pain with lock-files being incompatible between patch versions.
Instead of manually specifing the pnpm version and running the pnpm setup action is replaced with simply enableing corepack.
=> chore: use corepack instead of pnpm setup action in ci

next-themes/src/index.tsx
**Before**
```tsx
import { ThemeProvider, useTheme } from 'next-themes'
export type ThemeProviderProps = React.ComponentProps<typeof ThemeProvider>
export function ColorModeProvider(props: ThemeProviderProps) {
return <ThemeProvider attribute="class" disableTransitionOnChange {...props} />
}
```
**After**
```tsx
import { ThemeProvider, useTheme, type ThemeProviderProps } from 'next-themes'
export function ColorModeProvider(props: ThemeProviderProps) {
return <ThemeProvider attribute="class" disableTransitionOnChange {...props} />
}
```
=> Re-export types from `next-themes`

next-themes/src/index.tsx
There was an issue where sometimes the theme change would fall into infinite loop switching between the light/dark theme causing constant flashing. This issue could be reproduced by opening multiple tabs of the same app and quickly changing the theme many times. 
The root cause was that the "storage" listener in tab A would update the local storage, so the tab B would get an event and update the local storage, and then tab A would get an event...and so on. Somewhere along the way had to be some kind of race condition where the theme between the tabs would get out of sync causing the constant flashing back and forth.
To fix that I've swapped the `setTheme` with `setThemeState` in the storage listener, and only use `setTheme` to handle the case where the local storage entry is manually …
=> fix: infinite loop theme flicker

next-themes/src/script.ts
I think this is a bug: the CSS classes are being correctly remapped in order to _remove_ them all, but the class being added is not mapped using the `ValueObject`:
https://github.com/pacocoursey/next-themes/blob/57c0561b1fac95fab0a951adf1bc74f21e24c91c/next-themes/src/script.ts#L19-L22
=> fix: map theme to class using ValueObject in injected script

next-themes/src/index.tsx
Hey! Was checking some react profiles and saw that this sort of forcibly causes an extra render if setTheme hasn't been called before. This code change saves that by pre-resolving it to the right one.
=> Reduce number of renders by pre-setting resolvedTheme

next-themes/src/script.ts
This pull request addresses a potential issue in the `updateDOM` function where accessing the `value[theme]` property could result in a runtime error if `value` is `null` or `undefined`. The fix introduces a null check to ensure `value` is truthy before accessing its properties. Additionally, this change prevents flashing of themes by ensuring that the class list updates correctly.
- Updated the `updateDOM` function to use the following check:
```javascript
el.classList.add(value && value[theme] ? value[theme] : theme);
```
The previous implementation did not account for the possibility of `value` being `null` or `undefined`, which could lead to runtime errors. This fix makes the code more robust by preventing such errors. It also addresses the issue of theme flashing by ensuring that the …
=> fix: add null check for value in updateDOM function to prevent runtime errors and flashing

next-themes/__tests__/index.test.tsx, next-themes/src/index.tsx
This PR fixes the issue I mentioned here [#346](https://github.com/pacocoursey/next-themes/issues/346).
When passing a function to `setTheme`, it receives an outdated state value. This happens because the function is closed over `theme`, leading to incorrect behavior when updating the theme multiple times within the same render cycle. Each `setState` call computes the same value instead of using the latest state.  
- Rewrote the `setTheme` function to ensure it correctly handles functional updates.  
- Added tests to cover this edge case.  
This fix ensures that `setTheme` behaves as expected when called multiple times in a single render.
=> fix: #346 ensure `setTheme` Receives the Latest State
